ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT;
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "Application" ADD COLUMN IF NOT EXISTS "reviewedById" INTEGER;
